/**
 * Dialogs for the bank-keys surface:
 *   BankKeyFormDialog   — rename / reassign a physical token (identity fields
 *                         are read-only: they come from the connector inventory)
 *   ConnectorFormDialog — create / edit a connector machine; the token is
 *                         generated by the connector app and PASTED here
 *                         (relay INTEGRATION.md, operator flow §5)
 * Destructive confirms reuse ConfirmDialog from ../admin-dialogs.
 */
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";

import { useKeyCompanies, useKmUsers } from "../api";
import { apiErrorText } from "../admin-dialogs";
import {
  SIGNING_STACKS, useSaveConnector, useSetBankKeyUsers, useUpdateBankKey,
  type BankKeyInfo, type BankKeyWrite, type ConnectorInfo,
} from "./api";

const NO_COMPANY = "none";
const NO_STACK = "unknown";

export function BankKeyFormDialog({
  open, onOpenChange, bankKey,
}: {
  open: boolean; onOpenChange: (v: boolean) => void; bankKey: BankKeyInfo | null;
}) {
  const { t } = useTranslation();
  const { data: companies } = useKeyCompanies();
  const save = useUpdateBankKey();
  const [form, setForm] = useState<BankKeyWrite | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    if (open && bankKey) {
      setForm({
        id: bankKey.id, name: bankKey.name, bank_name: bankKey.bank_name,
        signing_stack: bankKey.signing_stack, company_id: bankKey.company_id,
      });
      setErr(null);
    }
  }, [open, bankKey]);

  const submit = async () => {
    if (!form) return;
    setErr(null);
    try { await save.mutateAsync(form); onOpenChange(false); }
    catch (e) { setErr(apiErrorText(e)); }
  };

  if (!form) return null;
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>{t("modules.keys.bankKeys.dialogs.editKey")}</DialogTitle>
          <DialogDescription>{t("modules.keys.bankKeys.dialogs.editKeyHint")}</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <Field label={t("modules.keys.bankKeys.dialogs.name")}>
            <Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
          </Field>
          <Field label={t("modules.keys.bankKeys.dialogs.bankName")}>
            <Input value={form.bank_name} onChange={(e) => setForm({ ...form, bank_name: e.target.value })} />
          </Field>
          <Field label={t("modules.keys.bankKeys.dialogs.signingStack")}>
            <Select
              value={form.signing_stack || NO_STACK}
              onValueChange={(v) => setForm({ ...form, signing_stack: (v === NO_STACK ? "" : v) as BankKeyWrite["signing_stack"] })}
            >
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value={NO_STACK}>—</SelectItem>
                {SIGNING_STACKS.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
              </SelectContent>
            </Select>
          </Field>
          <Field label={t("modules.keys.bankKeys.dialogs.company")}>
            <Select
              value={form.company_id != null ? String(form.company_id) : NO_COMPANY}
              onValueChange={(v) => setForm({ ...form, company_id: v === NO_COMPANY ? null : Number(v) })}
            >
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value={NO_COMPANY}>{t("modules.keys.admin.noCompany", { defaultValue: "—" })}</SelectItem>
                {(companies ?? []).map((c) => (
                  <SelectItem key={c.id} value={String(c.id)}>{c.name || `#${c.id}`}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>
          {err && <ErrorLine text={err} />}
          <div className="flex justify-end gap-2 pt-1">
            <Button variant="outline" onClick={() => onOpenChange(false)}>{t("common.cancel")}</Button>
            <Button onClick={submit} disabled={save.isPending || !form.name.trim()}>
              {save.isPending && <Loader2 className="size-4 mr-1 animate-spin" />}
              {t("common.save")}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export function ConnectorFormDialog({
  open, onOpenChange, connector,
}: {
  open: boolean; onOpenChange: (v: boolean) => void; connector: ConnectorInfo | null;
}) {
  const { t } = useTranslation();
  const save = useSaveConnector();
  const [name, setName] = useState("");
  const [token, setToken] = useState("");
  const [note, setNote] = useState("");
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    if (open) {
      setName(connector?.name ?? "");
      setToken("");
      setNote(connector?.note ?? "");
      setErr(null);
    }
  }, [open, connector]);

  const submit = async () => {
    setErr(null);
    try {
      await save.mutateAsync({
        id: connector?.id, name: name.trim(), token: token.trim(), note: note.trim(),
      });
      onOpenChange(false);
    } catch (e) { setErr(apiErrorText(e)); }
  };

  const canSubmit = name.trim().length > 0 && (connector != null || token.trim().length > 0);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>
            {connector
              ? t("modules.keys.bankKeys.dialogs.editConnector")
              : t("modules.keys.bankKeys.dialogs.addConnector")}
          </DialogTitle>
          <DialogDescription>{t("modules.keys.bankKeys.dialogs.connectorHint")}</DialogDescription>
        </DialogHeader>

        <div className="space-y-3">
          <Field label={t("modules.keys.bankKeys.dialogs.name")}>
            <Input value={name} onChange={(e) => setName(e.target.value)} autoFocus />
          </Field>
          <Field label={t("modules.keys.bankKeys.dialogs.token")}>
            <Input
              value={token}
              onChange={(e) => setToken(e.target.value)}
              className="font-mono"
              placeholder={connector
                ? t("modules.keys.bankKeys.dialogs.tokenKeep")
                : t("modules.keys.bankKeys.dialogs.tokenPlaceholder")}
            />
            <p className="text-xs text-muted-foreground pt-1">
              {t("modules.keys.bankKeys.dialogs.tokenHint")}
            </p>
          </Field>
          <Field label={t("modules.keys.bankKeys.dialogs.note")}>
            <Input value={note} onChange={(e) => setNote(e.target.value)} />
          </Field>
          {err && <ErrorLine text={err} />}
          <div className="flex justify-end gap-2 pt-1">
            <Button variant="outline" onClick={() => onOpenChange(false)}>{t("common.cancel")}</Button>
            <Button onClick={submit} disabled={save.isPending || !canSubmit}>
              {save.isPending && <Loader2 className="size-4 mr-1 animate-spin" />}
              {t("common.save")}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export function BankKeyUsersDialog({
  open, onOpenChange, bankKey,
}: {
  open: boolean; onOpenChange: (v: boolean) => void; bankKey: BankKeyInfo | null;
}) {
  const { t } = useTranslation();
  const { data: users, isLoading } = useKmUsers(open);
  const save = useSetBankKeyUsers();
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [q, setQ] = useState("");
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    if (open && bankKey) {
      setSelected(new Set(bankKey.attached_user_ids ?? []));
      setQ(""); setErr(null);
    }
  }, [open, bankKey]);

  const filtered = useMemo(() => {
    const term = q.trim().toLowerCase();
    const rows = users ?? [];
    if (!term) return rows;
    return rows.filter((u) =>
      [u.username, u.first_name, u.last_name, u.email]
        .filter(Boolean).some((v) => v.toLowerCase().includes(term)));
  }, [users, q]);

  const toggle = (id: number) => {
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  const submit = async () => {
    if (!bankKey) return;
    setErr(null);
    try {
      await save.mutateAsync({ id: bankKey.id, user_ids: [...selected] });
      onOpenChange(false);
    } catch (e) { setErr(apiErrorText(e)); }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>{t("modules.keys.admin.keyUsers")}</DialogTitle>
          <DialogDescription>{t("modules.keys.admin.keyUsersHint")}</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <Input value={q} onChange={(e) => setQ(e.target.value)}
            placeholder={t("modules.keys.admin.userSearch")} />
          <div className="max-h-64 overflow-y-auto rounded-md border border-border divide-y divide-border">
            {isLoading && (
              <div className="p-3 space-y-2">
                {Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-5 w-full" />)}
              </div>
            )}
            {!isLoading && filtered.length === 0 && (
              <div className="p-4 text-sm text-muted-foreground text-center">
                {t("modules.keys.admin.noUsers")}
              </div>
            )}
            {!isLoading && filtered.map((u) => (
              <label key={u.id}
                className="flex items-center gap-2.5 px-3 py-2 text-sm cursor-pointer hover:bg-muted/50">
                <Checkbox className="size-4" checked={selected.has(u.id)}
                  onCheckedChange={() => toggle(u.id)} />
                <span className="min-w-0">
                  <span className="font-medium">{u.username}</span>
                  {(u.first_name || u.last_name) && (
                    <span className="text-muted-foreground"> · {[u.first_name, u.last_name].filter(Boolean).join(" ")}</span>
                  )}
                  {u.role && u.role !== "user" && (
                    <span className="text-xs text-muted-foreground"> ({u.role})</span>
                  )}
                </span>
              </label>
            ))}
          </div>
          {err && <ErrorLine text={err} />}
          <div className="flex justify-end gap-2 pt-1">
            <Button variant="outline" onClick={() => onOpenChange(false)} disabled={save.isPending}>
              {t("common.cancel")}
            </Button>
            <Button onClick={submit} disabled={save.isPending || isLoading}>
              {save.isPending && <Loader2 className="size-4 mr-1 animate-spin" />}
              {t("common.save")}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block space-y-1.5">
      <span className="text-sm font-medium">{label}</span>
      {children}
    </label>
  );
}

function ErrorLine({ text }: { text: string }) {
  return (
    <div className="rounded-md border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
      {text}
    </div>
  );
}
