// Curated inline emoji dataset for the Telegram composer picker.
//
// We deliberately embed the data instead of adding an npm dependency (no
// emoji-mart / emojibase in package.json). This is a hand-picked subset of the
// most-used emoji — a few hundred glyphs across the standard categories, each
// tagged with English search keywords (space-separated, lowercase). It is not
// the full Unicode set (~3600); it is the common working set a chat composer
// actually needs. Emoji render with the system font (native), no images.
//
// Category ids match the picker's tab order. "recent" is synthesised at runtime
// from localStorage and is not present here.
export type EmojiEntry = { e: string; k: string };
export type EmojiGroup = { id: string; emojis: EmojiEntry[] };

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: "people",
    emojis: [
      { e: "😀", k: "grinning face smile happy" },
      { e: "😃", k: "smiley happy joy grin" },
      { e: "😄", k: "smile happy joy laugh" },
      { e: "😁", k: "grin beaming happy" },
      { e: "😆", k: "laughing satisfied haha" },
      { e: "😅", k: "sweat smile relief nervous" },
      { e: "🤣", k: "rofl rolling laughing lol" },
      { e: "😂", k: "joy tears laughing lol" },
      { e: "🙂", k: "slightly smiling face" },
      { e: "🙃", k: "upside down silly sarcasm" },
      { e: "😉", k: "wink flirt" },
      { e: "😊", k: "blush smile happy shy" },
      { e: "😇", k: "innocent angel halo" },
      { e: "🥰", k: "love hearts adore smiling" },
      { e: "😍", k: "heart eyes love crush" },
      { e: "🤩", k: "star struck excited amazed" },
      { e: "😘", k: "kiss blow love" },
      { e: "😗", k: "kissing" },
      { e: "😚", k: "kissing closed eyes" },
      { e: "😋", k: "yum savoring tasty delicious" },
      { e: "😛", k: "tongue playful" },
      { e: "😜", k: "wink tongue crazy joke" },
      { e: "🤪", k: "zany goofy wild silly" },
      { e: "😝", k: "tongue squint yum" },
      { e: "🤑", k: "money mouth rich dollar" },
      { e: "🤗", k: "hug hugging" },
      { e: "🤭", k: "hand over mouth oops giggle" },
      { e: "🤫", k: "shush quiet silence secret" },
      { e: "🤔", k: "thinking hmm consider" },
      { e: "🤐", k: "zipper mouth quiet" },
      { e: "🤨", k: "raised eyebrow skeptic" },
      { e: "😐", k: "neutral face meh" },
      { e: "😑", k: "expressionless blank" },
      { e: "😶", k: "no mouth silent speechless" },
      { e: "😏", k: "smirk smug" },
      { e: "😒", k: "unamused meh annoyed" },
      { e: "🙄", k: "rolling eyes annoyed" },
      { e: "😬", k: "grimace awkward" },
      { e: "😌", k: "relieved calm content" },
      { e: "😔", k: "pensive sad dejected" },
      { e: "😪", k: "sleepy tired" },
      { e: "🤤", k: "drooling hungry" },
      { e: "😴", k: "sleeping zzz tired" },
      { e: "😷", k: "mask sick ill face" },
      { e: "🤒", k: "sick thermometer fever" },
      { e: "🤕", k: "hurt bandage injured" },
      { e: "🤢", k: "nauseated sick gross" },
      { e: "🤮", k: "vomit puke sick" },
      { e: "🤧", k: "sneeze sick tissue" },
      { e: "🥵", k: "hot heat sweating" },
      { e: "🥶", k: "cold freezing frozen" },
      { e: "😵", k: "dizzy knocked out" },
      { e: "🤯", k: "mind blown shocked exploding" },
      { e: "🤠", k: "cowboy hat" },
      { e: "🥳", k: "party celebrate hat" },
      { e: "😎", k: "cool sunglasses" },
      { e: "🤓", k: "nerd geek glasses" },
      { e: "🧐", k: "monocle inspect curious" },
      { e: "😕", k: "confused" },
      { e: "😟", k: "worried" },
      { e: "🙁", k: "frown sad slight" },
      { e: "😮", k: "open mouth surprised wow" },
      { e: "😯", k: "hushed surprised" },
      { e: "😲", k: "astonished shocked" },
      { e: "😳", k: "flushed embarrassed" },
      { e: "🥺", k: "pleading puppy eyes beg" },
      { e: "😦", k: "frowning open mouth" },
      { e: "😨", k: "fearful scared" },
      { e: "😰", k: "anxious sweat nervous" },
      { e: "😥", k: "sad disappointed relieved" },
      { e: "😢", k: "cry tear sad" },
      { e: "😭", k: "sob crying bawling" },
      { e: "😱", k: "scream fear shocked" },
      { e: "😖", k: "confounded" },
      { e: "😣", k: "persevere struggle" },
      { e: "😞", k: "disappointed sad" },
      { e: "😓", k: "sweat downcast" },
      { e: "😩", k: "weary tired" },
      { e: "😫", k: "tired exhausted" },
      { e: "🥱", k: "yawn bored sleepy" },
      { e: "😤", k: "triumph huff steam angry" },
      { e: "😡", k: "rage angry mad red" },
      { e: "😠", k: "angry mad" },
      { e: "🤬", k: "cursing swearing angry" },
      { e: "😈", k: "devil smiling horns" },
      { e: "👿", k: "imp angry devil" },
      { e: "💀", k: "skull death dead" },
      { e: "💩", k: "poop shit crap" },
      { e: "🤡", k: "clown" },
      { e: "👻", k: "ghost boo halloween" },
      { e: "👽", k: "alien ufo" },
      { e: "🤖", k: "robot bot" },
      { e: "😺", k: "cat grinning happy" },
      { e: "😻", k: "cat heart eyes love" },
      { e: "🙀", k: "cat weary shocked" },
      { e: "👍", k: "thumbs up like yes approve" },
      { e: "👎", k: "thumbs down dislike no" },
      { e: "👌", k: "ok okay perfect" },
      { e: "🤌", k: "pinched fingers italian" },
      { e: "✌️", k: "victory peace fingers" },
      { e: "🤞", k: "crossed fingers luck hope" },
      { e: "🤟", k: "love you gesture" },
      { e: "🤘", k: "rock horns metal" },
      { e: "🤙", k: "call me hang loose" },
      { e: "👈", k: "point left" },
      { e: "👉", k: "point right" },
      { e: "👆", k: "point up" },
      { e: "👇", k: "point down" },
      { e: "☝️", k: "index up point" },
      { e: "👋", k: "wave hello hi bye" },
      { e: "🤚", k: "raised back hand" },
      { e: "✋", k: "raised hand stop high five" },
      { e: "🖐️", k: "hand fingers splayed" },
      { e: "🖖", k: "vulcan spock" },
      { e: "👏", k: "clap applause bravo" },
      { e: "🙌", k: "raised hands celebrate praise" },
      { e: "👐", k: "open hands" },
      { e: "🤲", k: "palms up together pray" },
      { e: "🙏", k: "pray thanks please folded hands" },
      { e: "🤝", k: "handshake deal agreement" },
      { e: "💪", k: "muscle flex strong biceps" },
      { e: "✍️", k: "writing hand" },
      { e: "👊", k: "fist bump punch" },
      { e: "✊", k: "raised fist power" },
      { e: "🤛", k: "left fist bump" },
      { e: "🤜", k: "right fist bump" },
      { e: "👶", k: "baby infant" },
      { e: "🧒", k: "child kid" },
      { e: "🧑", k: "person adult" },
      { e: "👨", k: "man male" },
      { e: "👩", k: "woman female" },
      { e: "🧓", k: "older person elderly" },
      { e: "👮", k: "police officer cop" },
      { e: "🕵️", k: "detective spy" },
      { e: "👷", k: "construction worker builder" },
      { e: "🤴", k: "prince royal" },
      { e: "👸", k: "princess royal" },
      { e: "🦸", k: "superhero" },
      { e: "🦹", k: "supervillain" },
      { e: "🧙", k: "wizard mage magic" },
      { e: "🧚", k: "fairy" },
      { e: "🎅", k: "santa christmas" },
      { e: "💃", k: "dancer dancing woman" },
      { e: "🕺", k: "dancer dancing man" },
      { e: "🧘", k: "yoga meditation zen" },
      { e: "👀", k: "eyes look watching" },
      { e: "❤️", k: "red heart love" },
      { e: "🧡", k: "orange heart" },
      { e: "💛", k: "yellow heart" },
      { e: "💚", k: "green heart" },
      { e: "💙", k: "blue heart" },
      { e: "💜", k: "purple heart" },
      { e: "🖤", k: "black heart" },
      { e: "🤍", k: "white heart" },
      { e: "💔", k: "broken heart heartbreak" },
      { e: "❣️", k: "heart exclamation" },
      { e: "💕", k: "two hearts love" },
      { e: "💖", k: "sparkling heart" },
      { e: "💗", k: "growing heart" },
      { e: "💘", k: "heart arrow cupid" },
      { e: "💝", k: "heart gift ribbon" },
    ],
  },
  {
    id: "nature",
    emojis: [
      { e: "🐶", k: "dog puppy pet" },
      { e: "🐱", k: "cat kitten pet" },
      { e: "🐭", k: "mouse" },
      { e: "🐹", k: "hamster" },
      { e: "🐰", k: "rabbit bunny" },
      { e: "🦊", k: "fox" },
      { e: "🐻", k: "bear" },
      { e: "🐼", k: "panda" },
      { e: "🐨", k: "koala" },
      { e: "🐯", k: "tiger" },
      { e: "🦁", k: "lion" },
      { e: "🐮", k: "cow" },
      { e: "🐷", k: "pig" },
      { e: "🐸", k: "frog" },
      { e: "🐵", k: "monkey" },
      { e: "🐔", k: "chicken hen" },
      { e: "🐧", k: "penguin" },
      { e: "🐦", k: "bird" },
      { e: "🐤", k: "chick baby bird" },
      { e: "🦆", k: "duck" },
      { e: "🦅", k: "eagle" },
      { e: "🦉", k: "owl" },
      { e: "🦇", k: "bat" },
      { e: "🐺", k: "wolf" },
      { e: "🐗", k: "boar" },
      { e: "🐴", k: "horse" },
      { e: "🦄", k: "unicorn" },
      { e: "🐝", k: "bee honeybee" },
      { e: "🐛", k: "bug caterpillar" },
      { e: "🦋", k: "butterfly" },
      { e: "🐌", k: "snail" },
      { e: "🐞", k: "ladybug" },
      { e: "🐜", k: "ant" },
      { e: "🕷️", k: "spider" },
      { e: "🐢", k: "turtle tortoise" },
      { e: "🐍", k: "snake" },
      { e: "🦎", k: "lizard" },
      { e: "🐙", k: "octopus" },
      { e: "🦑", k: "squid" },
      { e: "🦐", k: "shrimp" },
      { e: "🦀", k: "crab" },
      { e: "🐡", k: "blowfish pufferfish" },
      { e: "🐠", k: "tropical fish" },
      { e: "🐟", k: "fish" },
      { e: "🐬", k: "dolphin" },
      { e: "🐳", k: "whale spouting" },
      { e: "🦈", k: "shark" },
      { e: "🐊", k: "crocodile alligator" },
      { e: "🐅", k: "tiger" },
      { e: "🦓", k: "zebra" },
      { e: "🦍", k: "gorilla" },
      { e: "🐘", k: "elephant" },
      { e: "🦏", k: "rhino rhinoceros" },
      { e: "🐫", k: "camel" },
      { e: "🦒", k: "giraffe" },
      { e: "🐄", k: "cow" },
      { e: "🐎", k: "horse racehorse" },
      { e: "🐖", k: "pig" },
      { e: "🐑", k: "sheep" },
      { e: "🐐", k: "goat" },
      { e: "🦌", k: "deer" },
      { e: "🐕", k: "dog" },
      { e: "🐈", k: "cat" },
      { e: "🐓", k: "rooster" },
      { e: "🦃", k: "turkey" },
      { e: "🕊️", k: "dove peace bird" },
      { e: "🐇", k: "rabbit" },
      { e: "🐁", k: "mouse" },
      { e: "🌸", k: "cherry blossom flower pink" },
      { e: "🌹", k: "rose flower red love" },
      { e: "🌻", k: "sunflower flower" },
      { e: "🌼", k: "flower blossom" },
      { e: "🌷", k: "tulip flower" },
      { e: "🌵", k: "cactus plant" },
      { e: "🌲", k: "evergreen tree pine" },
      { e: "🌳", k: "tree deciduous" },
      { e: "🌴", k: "palm tree" },
      { e: "🍀", k: "clover luck four leaf" },
      { e: "🍁", k: "maple leaf autumn fall" },
      { e: "🍂", k: "fallen leaves autumn" },
      { e: "🍃", k: "leaves wind" },
      { e: "🌍", k: "earth globe world" },
      { e: "🌙", k: "moon crescent night" },
      { e: "⭐", k: "star" },
      { e: "🌟", k: "glowing star sparkle" },
      { e: "✨", k: "sparkles shiny" },
      { e: "⚡", k: "lightning bolt zap" },
      { e: "🔥", k: "fire flame hot lit" },
      { e: "🌈", k: "rainbow pride" },
      { e: "☀️", k: "sun sunny" },
      { e: "⛅", k: "cloud sun partly" },
      { e: "☁️", k: "cloud" },
      { e: "🌧️", k: "rain cloud" },
      { e: "⛈️", k: "storm thunder" },
      { e: "❄️", k: "snowflake cold snow" },
      { e: "☃️", k: "snowman winter" },
      { e: "💧", k: "droplet water drop" },
      { e: "🌊", k: "wave ocean water sea" },
    ],
  },
  {
    id: "food",
    emojis: [
      { e: "🍏", k: "green apple fruit" },
      { e: "🍎", k: "red apple fruit" },
      { e: "🍐", k: "pear fruit" },
      { e: "🍊", k: "orange tangerine fruit" },
      { e: "🍋", k: "lemon fruit sour" },
      { e: "🍌", k: "banana fruit" },
      { e: "🍉", k: "watermelon fruit" },
      { e: "🍇", k: "grapes fruit" },
      { e: "🍓", k: "strawberry fruit" },
      { e: "🫐", k: "blueberries fruit" },
      { e: "🍒", k: "cherries fruit" },
      { e: "🍑", k: "peach fruit butt" },
      { e: "🥭", k: "mango fruit" },
      { e: "🍍", k: "pineapple fruit" },
      { e: "🥥", k: "coconut" },
      { e: "🥝", k: "kiwi fruit" },
      { e: "🍅", k: "tomato" },
      { e: "🍆", k: "eggplant aubergine" },
      { e: "🥑", k: "avocado" },
      { e: "🥦", k: "broccoli" },
      { e: "🥬", k: "leafy greens lettuce" },
      { e: "🥒", k: "cucumber pickle" },
      { e: "🌶️", k: "hot pepper chili spicy" },
      { e: "🌽", k: "corn maize" },
      { e: "🥕", k: "carrot" },
      { e: "🧄", k: "garlic" },
      { e: "🧅", k: "onion" },
      { e: "🥔", k: "potato" },
      { e: "🍞", k: "bread loaf" },
      { e: "🥐", k: "croissant" },
      { e: "🥖", k: "baguette bread" },
      { e: "🧀", k: "cheese" },
      { e: "🥚", k: "egg" },
      { e: "🍳", k: "fried egg cooking" },
      { e: "🥞", k: "pancakes" },
      { e: "🧇", k: "waffle" },
      { e: "🥓", k: "bacon" },
      { e: "🥩", k: "steak meat" },
      { e: "🍗", k: "poultry leg chicken drumstick" },
      { e: "🍖", k: "meat bone" },
      { e: "🌭", k: "hotdog" },
      { e: "🍔", k: "hamburger burger" },
      { e: "🍟", k: "fries chips" },
      { e: "🍕", k: "pizza" },
      { e: "🥪", k: "sandwich" },
      { e: "🌮", k: "taco mexican" },
      { e: "🌯", k: "burrito wrap" },
      { e: "🥗", k: "salad" },
      { e: "🍜", k: "ramen noodles soup" },
      { e: "🍲", k: "stew pot food" },
      { e: "🍛", k: "curry rice" },
      { e: "🍣", k: "sushi" },
      { e: "🍱", k: "bento box" },
      { e: "🥟", k: "dumpling" },
      { e: "🍤", k: "shrimp fried tempura" },
      { e: "🍙", k: "rice ball onigiri" },
      { e: "🍚", k: "rice cooked" },
      { e: "🍦", k: "ice cream soft serve" },
      { e: "🍨", k: "ice cream" },
      { e: "🍧", k: "shaved ice" },
      { e: "🥧", k: "pie" },
      { e: "🧁", k: "cupcake" },
      { e: "🍰", k: "cake slice shortcake" },
      { e: "🎂", k: "birthday cake" },
      { e: "🍮", k: "custard flan pudding" },
      { e: "🍭", k: "lollipop candy" },
      { e: "🍬", k: "candy sweet" },
      { e: "🍫", k: "chocolate bar" },
      { e: "🍿", k: "popcorn" },
      { e: "🍩", k: "donut doughnut" },
      { e: "🍪", k: "cookie biscuit" },
      { e: "☕", k: "coffee tea hot drink" },
      { e: "🍵", k: "tea green" },
      { e: "🧃", k: "juice box" },
      { e: "🥤", k: "cup straw soda drink" },
      { e: "🍺", k: "beer mug" },
      { e: "🍻", k: "beers cheers" },
      { e: "🥂", k: "champagne cheers toast" },
      { e: "🍷", k: "wine glass" },
      { e: "🥃", k: "whiskey tumbler" },
      { e: "🍸", k: "cocktail martini" },
      { e: "🍹", k: "tropical drink cocktail" },
    ],
  },
  {
    id: "activity",
    emojis: [
      { e: "⚽", k: "soccer football ball" },
      { e: "🏀", k: "basketball ball" },
      { e: "🏈", k: "american football" },
      { e: "⚾", k: "baseball" },
      { e: "🥎", k: "softball" },
      { e: "🎾", k: "tennis" },
      { e: "🏐", k: "volleyball" },
      { e: "🏉", k: "rugby" },
      { e: "🥏", k: "frisbee disc" },
      { e: "🎱", k: "pool 8 ball billiards" },
      { e: "🏓", k: "ping pong table tennis" },
      { e: "🏸", k: "badminton" },
      { e: "🏒", k: "ice hockey" },
      { e: "🏑", k: "field hockey" },
      { e: "🏏", k: "cricket" },
      { e: "⛳", k: "golf flag" },
      { e: "🏹", k: "bow arrow archery" },
      { e: "🎣", k: "fishing" },
      { e: "🥊", k: "boxing glove" },
      { e: "🥋", k: "martial arts karate judo" },
      { e: "🛹", k: "skateboard" },
      { e: "⛸️", k: "ice skate" },
      { e: "🎿", k: "ski" },
      { e: "🏂", k: "snowboard" },
      { e: "🏆", k: "trophy win champion" },
      { e: "🥇", k: "gold medal first" },
      { e: "🥈", k: "silver medal second" },
      { e: "🥉", k: "bronze medal third" },
      { e: "🏅", k: "medal sports" },
      { e: "🎖️", k: "military medal honor" },
      { e: "🎫", k: "ticket" },
      { e: "🎪", k: "circus tent" },
      { e: "🎭", k: "performing arts theater masks" },
      { e: "🎨", k: "art palette paint" },
      { e: "🎬", k: "clapper movie film" },
      { e: "🎤", k: "microphone sing karaoke" },
      { e: "🎧", k: "headphones music" },
      { e: "🎼", k: "musical score notes" },
      { e: "🎹", k: "piano keyboard music" },
      { e: "🥁", k: "drum" },
      { e: "🎷", k: "saxophone" },
      { e: "🎺", k: "trumpet" },
      { e: "🎸", k: "guitar" },
      { e: "🎻", k: "violin" },
      { e: "🎲", k: "dice game" },
      { e: "♟️", k: "chess pawn" },
      { e: "🎯", k: "dart target bullseye" },
      { e: "🎳", k: "bowling" },
      { e: "🎮", k: "video game controller gaming" },
      { e: "🕹️", k: "joystick game" },
      { e: "🎰", k: "slot machine gamble" },
      { e: "🧩", k: "puzzle piece" },
      { e: "🎨", k: "paint art palette" },
      { e: "🎉", k: "party popper celebrate tada" },
      { e: "🎊", k: "confetti ball party" },
      { e: "🎈", k: "balloon party" },
      { e: "🎁", k: "gift present box" },
    ],
  },
  {
    id: "travel",
    emojis: [
      { e: "🚗", k: "car automobile" },
      { e: "🚕", k: "taxi cab" },
      { e: "🚙", k: "suv car" },
      { e: "🚌", k: "bus" },
      { e: "🏎️", k: "race car formula" },
      { e: "🚓", k: "police car" },
      { e: "🚑", k: "ambulance" },
      { e: "🚒", k: "fire truck" },
      { e: "🚚", k: "truck delivery" },
      { e: "🚛", k: "lorry truck" },
      { e: "🚜", k: "tractor farm" },
      { e: "🏍️", k: "motorcycle" },
      { e: "🚲", k: "bicycle bike" },
      { e: "🛴", k: "scooter kick" },
      { e: "🚨", k: "siren police alert" },
      { e: "✈️", k: "airplane flight travel" },
      { e: "🛫", k: "airplane departure takeoff" },
      { e: "🛬", k: "airplane arrival landing" },
      { e: "🚀", k: "rocket space launch" },
      { e: "🛸", k: "ufo flying saucer" },
      { e: "🚁", k: "helicopter" },
      { e: "⛵", k: "sailboat sailing" },
      { e: "🚤", k: "speedboat" },
      { e: "🛳️", k: "cruise ship passenger" },
      { e: "🚢", k: "ship" },
      { e: "⚓", k: "anchor" },
      { e: "🚦", k: "traffic light" },
      { e: "🗺️", k: "map world" },
      { e: "🗽", k: "statue of liberty new york" },
      { e: "🗼", k: "tokyo tower" },
      { e: "🏰", k: "castle" },
      { e: "🏯", k: "japanese castle" },
      { e: "🎡", k: "ferris wheel" },
      { e: "🎢", k: "roller coaster" },
      { e: "🎠", k: "carousel merry go round" },
      { e: "⛲", k: "fountain" },
      { e: "🏖️", k: "beach umbrella" },
      { e: "🏝️", k: "desert island beach" },
      { e: "🌋", k: "volcano" },
      { e: "⛰️", k: "mountain" },
      { e: "🏔️", k: "snow mountain" },
      { e: "🏕️", k: "camping tent" },
      { e: "⛺", k: "tent camping" },
      { e: "🏠", k: "house home" },
      { e: "🏡", k: "house garden home" },
      { e: "🏢", k: "office building" },
      { e: "🏬", k: "department store" },
      { e: "🏥", k: "hospital" },
      { e: "🏦", k: "bank" },
      { e: "🏨", k: "hotel" },
      { e: "🏫", k: "school" },
      { e: "🌆", k: "city dusk buildings" },
      { e: "🌃", k: "night city stars" },
      { e: "🌉", k: "bridge night" },
      { e: "🗿", k: "moai statue easter island" },
      { e: "🌐", k: "globe meridians internet" },
    ],
  },
  {
    id: "objects",
    emojis: [
      { e: "⌚", k: "watch time" },
      { e: "📱", k: "phone mobile smartphone" },
      { e: "💻", k: "laptop computer" },
      { e: "⌨️", k: "keyboard" },
      { e: "🖥️", k: "desktop computer monitor" },
      { e: "🖨️", k: "printer" },
      { e: "🖱️", k: "mouse computer" },
      { e: "💾", k: "floppy disk save" },
      { e: "💿", k: "cd disc" },
      { e: "📷", k: "camera photo" },
      { e: "📸", k: "camera flash photo" },
      { e: "📹", k: "video camera" },
      { e: "🎥", k: "movie camera film" },
      { e: "📺", k: "tv television" },
      { e: "📻", k: "radio" },
      { e: "⏰", k: "alarm clock" },
      { e: "⏱️", k: "stopwatch timer" },
      { e: "🔋", k: "battery" },
      { e: "🔌", k: "plug electric power" },
      { e: "💡", k: "light bulb idea" },
      { e: "🔦", k: "flashlight torch" },
      { e: "🕯️", k: "candle" },
      { e: "🧯", k: "fire extinguisher" },
      { e: "💸", k: "money flying dollar" },
      { e: "💵", k: "dollar money cash" },
      { e: "💰", k: "money bag rich" },
      { e: "💳", k: "credit card payment" },
      { e: "💎", k: "diamond gem jewel" },
      { e: "⚖️", k: "scales justice balance" },
      { e: "🧰", k: "toolbox tools" },
      { e: "🔧", k: "wrench spanner tool" },
      { e: "🔨", k: "hammer tool" },
      { e: "🪛", k: "screwdriver" },
      { e: "🔩", k: "nut bolt" },
      { e: "⚙️", k: "gear settings cog" },
      { e: "🧱", k: "brick wall" },
      { e: "⛓️", k: "chains" },
      { e: "🔫", k: "gun water pistol" },
      { e: "💣", k: "bomb" },
      { e: "🔪", k: "knife blade cut" },
      { e: "🛡️", k: "shield protection" },
      { e: "🔮", k: "crystal ball fortune magic" },
      { e: "🧸", k: "teddy bear toy" },
      { e: "🎀", k: "ribbon bow" },
      { e: "✉️", k: "envelope email mail letter" },
      { e: "📧", k: "email mail" },
      { e: "📦", k: "package box parcel" },
      { e: "📝", k: "memo note writing" },
      { e: "✏️", k: "pencil write" },
      { e: "🖊️", k: "pen write" },
      { e: "📌", k: "pushpin pin" },
      { e: "📎", k: "paperclip attach" },
      { e: "📏", k: "ruler measure" },
      { e: "✂️", k: "scissors cut" },
      { e: "🗑️", k: "trash bin delete garbage" },
      { e: "🔒", k: "lock closed secure" },
      { e: "🔓", k: "unlock open" },
      { e: "🔑", k: "key" },
      { e: "🔔", k: "bell notification" },
      { e: "📚", k: "books" },
      { e: "📖", k: "open book read" },
      { e: "📅", k: "calendar date" },
      { e: "📈", k: "chart up growth" },
      { e: "📉", k: "chart down decline" },
      { e: "💊", k: "pill medicine drug" },
      { e: "🩺", k: "stethoscope doctor" },
      { e: "🧬", k: "dna" },
      { e: "🔬", k: "microscope science" },
      { e: "🔭", k: "telescope" },
    ],
  },
  {
    id: "symbols",
    emojis: [
      { e: "✅", k: "check mark green done yes" },
      { e: "❌", k: "cross x no wrong" },
      { e: "❎", k: "cross mark button" },
      { e: "➕", k: "plus add" },
      { e: "➖", k: "minus subtract" },
      { e: "➗", k: "divide division" },
      { e: "✖️", k: "multiply times" },
      { e: "♾️", k: "infinity" },
      { e: "‼️", k: "double exclamation" },
      { e: "⁉️", k: "exclamation question" },
      { e: "❓", k: "question mark" },
      { e: "❗", k: "exclamation mark" },
      { e: "⚠️", k: "warning caution alert" },
      { e: "🚸", k: "children crossing" },
      { e: "🔱", k: "trident emblem" },
      { e: "⚜️", k: "fleur de lis" },
      { e: "🔰", k: "beginner novice" },
      { e: "♻️", k: "recycle recycling" },
      { e: "✳️", k: "asterisk" },
      { e: "❇️", k: "sparkle" },
      { e: "💯", k: "hundred perfect score 100" },
      { e: "🎵", k: "music note" },
      { e: "🎶", k: "music notes" },
      { e: "💤", k: "zzz sleep sleeping" },
      { e: "💢", k: "anger symbol mad" },
      { e: "💥", k: "collision boom explosion" },
      { e: "💫", k: "dizzy star" },
      { e: "💦", k: "sweat droplets water" },
      { e: "💨", k: "dash wind fast" },
      { e: "🕳️", k: "hole" },
      { e: "💬", k: "speech balloon comment chat" },
      { e: "💭", k: "thought balloon thinking" },
      { e: "🗯️", k: "anger speech bubble" },
      { e: "♠️", k: "spades card" },
      { e: "♥️", k: "hearts card" },
      { e: "♦️", k: "diamonds card" },
      { e: "♣️", k: "clubs card" },
      { e: "🔴", k: "red circle" },
      { e: "🟠", k: "orange circle" },
      { e: "🟡", k: "yellow circle" },
      { e: "🟢", k: "green circle" },
      { e: "🔵", k: "blue circle" },
      { e: "🟣", k: "purple circle" },
      { e: "⚫", k: "black circle" },
      { e: "⚪", k: "white circle" },
      { e: "🟥", k: "red square" },
      { e: "🟩", k: "green square" },
      { e: "🟦", k: "blue square" },
      { e: "⬛", k: "black square" },
      { e: "⬜", k: "white square" },
      { e: "🔺", k: "red triangle up" },
      { e: "🔻", k: "red triangle down" },
      { e: "💠", k: "diamond dot" },
      { e: "🔘", k: "radio button" },
      { e: "🔗", k: "link chain" },
      { e: "➡️", k: "arrow right" },
      { e: "⬅️", k: "arrow left" },
      { e: "⬆️", k: "arrow up" },
      { e: "⬇️", k: "arrow down" },
      { e: "🔄", k: "refresh reload arrows" },
      { e: "🔝", k: "top up arrow" },
      { e: "🆕", k: "new" },
      { e: "🆗", k: "ok button" },
      { e: "🆒", k: "cool button" },
      { e: "🈵", k: "no vacancy full" },
      { e: "🚫", k: "prohibited no forbidden" },
      { e: "⭕", k: "circle no" },
      { e: "🔞", k: "no under 18 adult" },
    ],
  },
  {
    id: "flags",
    emojis: [
      { e: "🏁", k: "checkered flag finish race" },
      { e: "🚩", k: "triangular flag" },
      { e: "🎌", k: "crossed flags japan" },
      { e: "🏴", k: "black flag" },
      { e: "🏳️", k: "white flag surrender" },
      { e: "🏳️‍🌈", k: "rainbow flag pride lgbt" },
      { e: "🏴‍☠️", k: "pirate flag jolly roger" },
      { e: "🇺🇿", k: "uzbekistan uz flag" },
      { e: "🇷🇺", k: "russia ru flag" },
      { e: "🇺🇸", k: "usa united states america flag" },
      { e: "🇬🇧", k: "uk united kingdom britain flag" },
      { e: "🇰🇿", k: "kazakhstan kz flag" },
      { e: "🇰🇬", k: "kyrgyzstan flag" },
      { e: "🇹🇯", k: "tajikistan flag" },
      { e: "🇹🇲", k: "turkmenistan flag" },
      { e: "🇹🇷", k: "turkey turkiye flag" },
      { e: "🇨🇳", k: "china cn flag" },
      { e: "🇯🇵", k: "japan jp flag" },
      { e: "🇰🇷", k: "korea south flag" },
      { e: "🇩🇪", k: "germany de flag" },
      { e: "🇫🇷", k: "france fr flag" },
      { e: "🇮🇹", k: "italy it flag" },
      { e: "🇪🇸", k: "spain es flag" },
      { e: "🇮🇳", k: "india in flag" },
      { e: "🇧🇷", k: "brazil br flag" },
      { e: "🇦🇪", k: "uae emirates flag" },
      { e: "🇸🇦", k: "saudi arabia flag" },
      { e: "🇨🇦", k: "canada flag" },
      { e: "🇦🇺", k: "australia flag" },
      { e: "🇺🇦", k: "ukraine flag" },
    ],
  },
];
